package bg.softuni.travelProject.scheduling;

import bg.softuni.travelProject.model.enums.ContinentEnum;
import bg.softuni.travelProject.service.EmailService;
import bg.softuni.travelProject.service.TripService;
import bg.softuni.travelProject.service.UserService;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;

@Service
public class ReportService {

    private static final String REPORT_TITLE = "This is autogenerated message from your application.";
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ReportService.class);
    private final TripService tripService;
    private final EmailService emailService;
    private final UserService userService;

    public ReportService(TripService tripService, EmailService emailService, UserService userService) {
        this.tripService = tripService;
        this.emailService = emailService;
        this.userService = userService;
    }

    public void generateDailyReport() {
        LocalDate today = LocalDate.now();
        Instant todayMidnight = today.atStartOfDay(ZoneOffset.UTC).toInstant();

        log.info("Start generating report");

        String result = String.format("""
                        Report on date: %s
                            Asian trips: %d
                            African trips: %d
                            North American trips: %d
                            South American trips: %d
                            Antarctican trips: %d
                            European trips: %d
                            Australian trips: %d
                            All trips: %d
                        """, todayMidnight,
                tripService.findCountByContinent(ContinentEnum.ASIA),
                tripService.findCountByContinent(ContinentEnum.AFRICA),
                tripService.findCountByContinent(ContinentEnum.NORTH_AMERICA),
                tripService.findCountByContinent(ContinentEnum.SOUTH_AMERICA),
                tripService.findCountByContinent(ContinentEnum.ANTARCTICA),
                tripService.findCountByContinent(ContinentEnum.EUROPE),
                tripService.findCountByContinent(ContinentEnum.AUSTRALIA),
                tripService.findCountAll()
        );
        List<String> adminsEmails = this.userService.getAdminsEmails();
        for (String email : adminsEmails) {
            log.info(String.format("Report is sent to %s", email));
            emailService.sendSimpleMessage(email, REPORT_TITLE, result);
        }
    }
}
